Auth1/Projects/skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]


  root to: redirect('/cats')
end

Auth1/Projects/skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <% if !current_user.nil? %>
        <ul>
          <li>Logged in as: <%= current_user.username %></li>
          <li>
            <form action="<%= session_url%>" method="POST">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" value="delete" name="_method">
              <input type="submit" value="Logout">
            </form>
          </li>
        </ul>

      <% else %>
        <ul>
          <li>
            <%= link_to "New User", new_user_url %> 
            <%= link_to "Login", new_session_url %>
          </li>
        </ul>
      <% end %>

      <%= link_to "Cats", cats_url %>
      <%= link_to "New Cat", new_cat_url%>
      <%= link_to "New Request", new_cat_rental_request_url %>
    </nav>
    <%= yield %>
  </body>
</html>