Testing/Homework/Music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end


  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy, :update, :new]


end

Testing/Homework/Music/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  track_id   :integer          not null
#  user_id    :integer          not null
#
class Note < ApplicationRecord

    belongs_to :user
    belongs_to :track

end

Testing/Homework/Music/app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def new

    end

    def create
        @note = Note.new(note_params)
        @note.user_id = current_user.id
        @note.save!

        redirect_to track_url(@note.track_id)
    end

    def update

    end

    def destroy

        if @note.user_id != current_user.id
            render text: "FORBIDDEN EXODIA"
        end
        
        @note = Note.find(params[:id])
        @note.destroy

        redirect_to track_url(@note.track_id)

    end

    def note_params
        params.require(:note).permit(:body, :track_id)
    end
end

Testing/Homework/Music/app/views/notes/_form.html.erb
<section> 
    <form action="<%= notes_url %>" method="POST">

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="note[track_id]" value="<%= @track.id %>">
        <label for="note">Add A Note:</label>
        <textarea name="note[body]" id="notes"></textarea>


        <input type="submit" value="Submit">
    </form>

</section>

Testing/Homework/Music/app/views/notes/_note.html.erb
<section>

    <% @notes.each do |note| %>
        <%= note.body %>
        <%= note.user.email %>
        <br>
        <% if note.user_id == current_user.id %>
            <form action="<%= note_url(note) %>" method="post">
                <input type="hidden" name="_method" value="delete">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="submit" value="Delete?">
            </form>
        <% end %>
    <% end %>
</section>