Testing/Homework/Music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end


  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy, :update, :new]


end

Testing/Homework/Music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

   <header>
  
    <h1>Botify</h1>

    <div style="margin: auto;">
      <a href="<%= new_band_url %>">Add Band</a>
    </div>

    <% if current_user.nil? %>

      <nav>
        <ul>
          <li><%= link_to "Home", bands_url %></li>
          <li><%= link_to "New User", new_user_url %></li>
          <li><%= link_to "Login", new_session_url %></li>
        </ul>
      <nav>

    <% else %>


      <ul>
          <li><%= link_to "Home", bands_url %></li>
      </ul>

      <h4> Logged in as: <%= current_user.email %> </h4>

      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" value="delete" name="_method">
        <input type="submit" value="Logout">
      </form>

    <% end %>

    
   </header>

    <%= yield %>


  </body>

  
</html>